spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kob
    username: root
    password: aoliao
server:
  port: 3300
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #???????????????